//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TMPCLP476291
    {
        public int Id { get; set; }
        public Nullable<int> id_smp { get; set; }
        public Nullable<int> id_epp { get; set; }
    }
}
