//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendarioPM
    {
        public int Id { get; set; }
        public Nullable<int> id_componente { get; set; }
        public Nullable<int> id_ewo { get; set; }
        public Nullable<int> tipo_mantenimiento { get; set; }
        public Nullable<int> semana { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
    }
}
