//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class componentes
    {
        public int Id { get; set; }
        public string codigo_fabricante { get; set; }
        public string codigo_sap { get; set; }
        public string descripcion { get; set; }
        public string ubicacion_almacen { get; set; }
        public string clase { get; set; }
        public string proveedor { get; set; }
        public Nullable<int> estrategia_mtto { get; set; }
        public Nullable<int> id_smp { get; set; }
        public Nullable<int> frecuencia_pm { get; set; }
        public Nullable<int> tipo_frecuencia_pm { get; set; }
        public Nullable<int> duracion_estandar { get; set; }
        public Nullable<int> estado_equipo { get; set; }
        public Nullable<int> estandar_am { get; set; }
        public Nullable<int> frecuencia_am { get; set; }
        public Nullable<int> tipo_frecuencia_am { get; set; }
        public string n_matriz_qp { get; set; }
        public string n_matriz_qm { get; set; }
        public Nullable<int> tipo_kaizen { get; set; }
        public Nullable<int> n_kaizen { get; set; }
        public string image_path { get; set; }
        public Nullable<int> id_conjunto { get; set; }
        public byte[] smp_file { get; set; }
    }
}
