//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MttoAppEntities : DbContext
    {
        public MttoAppEntities()
            : base("name=MttoAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calendario_tipomtto> calendario_tipomtto { get; set; }
        public virtual DbSet<calendarioPM> calendarioPM { get; set; }
        public virtual DbSet<componentes> componentes { get; set; }
        public virtual DbSet<conjuntos> conjuntos { get; set; }
        public virtual DbSet<epps> epps { get; set; }
        public virtual DbSet<equipos> equipos { get; set; }
        public virtual DbSet<herramientas> herramientas { get; set; }
        public virtual DbSet<lista_acciones> lista_acciones { get; set; }
        public virtual DbSet<maquinas> maquinas { get; set; }
        public virtual DbSet<permisos_trabajo> permisos_trabajo { get; set; }
        public virtual DbSet<plantas> plantas { get; set; }
        public virtual DbSet<porques> porques { get; set; }
        public virtual DbSet<programadores> programadores { get; set; }
        public virtual DbSet<repuestos_utilizados> repuestos_utilizados { get; set; }
        public virtual DbSet<sistemas> sistemas { get; set; }
        public virtual DbSet<smp> smp { get; set; }
        public virtual DbSet<smp_pasos> smp_pasos { get; set; }
        public virtual DbSet<smp_util> smp_util { get; set; }
        public virtual DbSet<tecnicos> tecnicos { get; set; }
        public virtual DbSet<tipo_averia> tipo_averia { get; set; }
        public virtual DbSet<tipos> tipos { get; set; }
        public virtual DbSet<tipos_data> tipos_data { get; set; }
        public virtual DbSet<turnos> turnos { get; set; }
        public virtual DbSet<lineas> lineas { get; set; }
        public virtual DbSet<sop_pasos> sop_pasos { get; set; }
        public virtual DbSet<sop_utils> sop_utils { get; set; }
        public virtual DbSet<sop> sop { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<C_TMPCLP476291> C_TMPCLP476291 { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<kpis> kpis { get; set; }
        public virtual DbSet<ewos> ewos { get; set; }
    }
}
