//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ewos
    {
        public int Id { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public Nullable<int> id_area_linea { get; set; }
        public Nullable<int> id_equipo { get; set; }
        public Nullable<System.DateTime> fecha_ewo { get; set; }
        public string aviso_numero { get; set; }
        public string id_tecnico { get; set; }
        public Nullable<int> id_tipo_averia { get; set; }
        public Nullable<int> id_turno { get; set; }
        public Nullable<System.DateTime> notificacion_averia { get; set; }
        public Nullable<System.DateTime> inicio_reparacion { get; set; }
        public Nullable<int> tiempo_espera_tecnico { get; set; }
        public Nullable<int> tiempo_diagnostico { get; set; }
        public Nullable<int> tiempo_espera_repuestos { get; set; }
        public Nullable<int> tiempo_reparacion { get; set; }
        public Nullable<int> tiempo_pruebas { get; set; }
        public Nullable<System.DateTime> fin_reparacion { get; set; }
        public Nullable<int> tiempo_total { get; set; }
        public string imagen_1 { get; set; }
        public string imagen_2 { get; set; }
        public string desc_imagen_1 { get; set; }
        public string desc_imagen_2 { get; set; }
        public string desc_averia { get; set; }
        public Nullable<bool> cambio_componente { get; set; }
        public Nullable<bool> ajuste { get; set; }
        public string what { get; set; }
        public string where { get; set; }
        public string when { get; set; }
        public string who { get; set; }
        public string wich { get; set; }
        public string how { get; set; }
        public string fenomeno { get; set; }
        public string gemba { get; set; }
        public Nullable<bool> gemba_ok { get; set; }
        public string gembutsu { get; set; }
        public Nullable<bool> gembutsu_ok { get; set; }
        public string genjitsu { get; set; }
        public Nullable<bool> genjitsu_ok { get; set; }
        public string genri { get; set; }
        public Nullable<bool> genri_ok { get; set; }
        public string gensoku { get; set; }
        public Nullable<bool> gensoku_ok { get; set; }
        public string imagen_3 { get; set; }
        public string imagen_4 { get; set; }
        public string desc_imagen_3 { get; set; }
        public string desc_imagen_4 { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_mtto { get; set; }
        public Nullable<System.DateTime> fecha_proximo_mtto { get; set; }
        public Nullable<int> falla_index { get; set; }
        public Nullable<int> causa_raiz_index { get; set; }
        public string tecnicos_man_involucrados { get; set; }
        public string operarios_involucrados { get; set; }
        public string elaborador_analisis { get; set; }
        public Nullable<System.DateTime> fecha_analisis { get; set; }
        public string definidor_contramedidas { get; set; }
        public Nullable<System.DateTime> fecha_contramedida { get; set; }
        public string validador_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_validacion { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> kpi { get; set; }
    }
}
