//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpis
    {
        public int id { get; set; }
        public Nullable<int> id_linea { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<decimal> tiempo_carga { get; set; }
        public Nullable<decimal> mttr { get; set; }
        public Nullable<decimal> mtbf { get; set; }
    
        public virtual lineas lineas { get; set; }
    }
}
