//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class maquinas
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string foto_path { get; set; }
        public Nullable<int> id_planta { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<int> id_linea { get; set; }
    }
}
