//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiales
    {
        public int id { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public string clase_movimiento { get; set; }
        public string material { get; set; }
        public string descripcion { get; set; }
        public string doc_material { get; set; }
        public string ctd_um_entrada { get; set; }
        public string un_medida_entrada { get; set; }
        public string cab_documento { get; set; }
    }
}
