//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class porques
    {
        public int Id { get; set; }
        public Nullable<int> id_ewo { get; set; }
        public string porque_1 { get; set; }
        public string porque_2 { get; set; }
        public string porque_3 { get; set; }
        public string porque_4 { get; set; }
        public string porque_5 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
