//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class smp
    {
        public int Id { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public string nombre { get; set; }
        public Nullable<long> numero { get; set; }
        public Nullable<int> id_linea { get; set; }
        public Nullable<int> id_equipo { get; set; }
        public Nullable<System.DateTime> feha_smp { get; set; }
        public Nullable<int> clasificacion { get; set; }
        public Nullable<int> tipo_mtto { get; set; }
        public Nullable<int> tecnicos_req { get; set; }
        public Nullable<int> duracion_actividad { get; set; }
        public Nullable<int> equipo_parado { get; set; }
        public Nullable<int> frecuencia { get; set; }
        public Nullable<int> tipo_frecuencia { get; set; }
        public Nullable<int> id_elaborador { get; set; }
        public Nullable<int> id_aprobador { get; set; }
        public Nullable<bool> loto { get; set; }
        public string permisos { get; set; }
        public string imagen_1 { get; set; }
        public string imagen_2 { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
