//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class smp_pasos
    {
        public int Id { get; set; }
        public string paso { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> duracion { get; set; }
        public string image_path { get; set; }
        public Nullable<int> categoria_id { get; set; }
        public Nullable<int> id_smp { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
