//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sop
    {
        public int id { get; set; }
        public string codigo_formato { get; set; }
        public Nullable<int> codigo_categoria { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public Nullable<int> numero_revision { get; set; }
        public Nullable<int> codigo_maquina { get; set; }
        public Nullable<int> codigo_tipo { get; set; }
        public Nullable<int> codigo_usuario_preparador { get; set; }
        public Nullable<int> codigo_area_aprobadora { get; set; }
        public Nullable<int> codigo_lider_area { get; set; }
        public Nullable<int> personas_requeridas { get; set; }
        public string tiempo_persona { get; set; }
        public string duracion_tarea { get; set; }
        public string maquina_parada { get; set; }
        public Nullable<int> codigo_frecuencia { get; set; }
        public string titulo { get; set; }
        public Nullable<int> numero_sop { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
