//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int id { get; set; }
        public string ubicacion { get; set; }
        public string material { get; set; }
        public string descripcion { get; set; }
        public string stock_total { get; set; }
        public string bun { get; set; }
        public string deposito { get; set; }
        public string precios_medio_movil { get; set; }
        public string valor_total { get; set; }
        public Nullable<int> planta { get; set; }
    }
}
