//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecnicos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> tipo_usuario { get; set; }
    }
}
