//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatoEwo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_data
    {
        public int Id { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public string descripcion { get; set; }
    
        public virtual tipos tipos { get; set; }
    }
}
